name: check-build

on: push

jobs:
  check-build:
    name: Check build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install repo
        run: yarn install
      - name: Build
        run: yarn bundle
