name: check-types

on: push

jobs:
  check-types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        run: yarn install
      - name: Run tsc
        run: yarn check-types

        
